# Generated by Django 3.2.8 on 2021-10-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('recommend', models.CharField(max_length=100)),
                ('fav_feature', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
    ]
